# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    freepost.asset:
        class: AppBundle\Service\Asset
        arguments: ["%repository_master_path%", "%repository_slave_host%"]
    
    freepost.string:
        class: AppBundle\Service\String
        arguments: []
    
    freepost.twig_extension:
        class: AppBundle\Twig\Extension\Filter\Repository
        arguments: ["@freepost.asset"]
        tags:
            - { name: twig.extension }
    
    freepost.doctrine.entity_listener_resolver:
        class: AppBundle\Doctrine\EntityListenerResolver
        arguments: ["@service_container"]
    
    freepost.entity_listener.comment:
        class: AppBundle\Entity\Listener\Comment
        arguments: ["@exercise_html_purifier.default", "@freepost.string"]
        tags:
            -  { name: doctrine.entity_listener }
    
    freepost.entity_listener.community:
        class: AppBundle\Entity\Listener\Community
        arguments: ["@exercise_html_purifier.default", "@freepost.string"]
        tags:
            -  { name: doctrine.entity_listener }
    
    freepost.entity_listener.post:
        class: AppBundle\Entity\Listener\Post
        arguments: ["@exercise_html_purifier.default", "@freepost.string"]
        tags:
            -  { name: doctrine.entity_listener }